# Generated by Django 5.0.3 on 2024-04-05 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='core.estoque'),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.perfil'),
        ),
    ]
