# Generated by Django 5.0.3 on 2024-04-23 23:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movimento',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.marca'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.UniqueConstraint(fields=('nome', 'unidade_medida', 'marca'), name='produto_unico'),
        ),
    ]
