# Generated by Django 5.0.3 on 2024-04-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marca_movimento_preco_alter_estoque_preco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidademedida',
            name='sigla',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
