# Generated by Django 5.0.3 on 2024-04-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_unidademedida_sigla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marca',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
